// Translations
// All keys are in english, values in spanish (default) and english.
const config = require('./config')

const lang = {
  es: {
    // common
    appname: config.appName,
    tagline: 'Ayuda a quien mas lo necesita',
    nav_home: 'Inicio',
    nav_campaigns: 'Ver campañas',
    nav_create: 'Crear campaña',
    nav_mycampaigns: 'Mis campañas',
    nav_dashboard: 'Panel',
    nav_login: 'Entrar',
    nav_register: 'Registrarse',
    nav_logout: 'Salir',
    nav_hello: 'Hola',
    footer_about: config.appName +' es una plataforma para crear campañas de donación y apoyar causas que transforman vidas',
    footer_links: 'Enlaces',
    footer_legal: 'Términos y privacidad',
    footer_contact: 'Contacto',
    footer_rights: 'Todos los derechos reservados',
    footer_lang: 'Idioma',
    lang_es: 'Español',
    lang_en: 'English',
    theme_light: 'Modo claro',
    theme_dark: 'Modo oscuro',

    // hero / landing
    hero_title: 'Sé parte del cambio',
    hero_subtitle: 'Crea una campaña de donación o apoya las causas que más te importan. Cada aporte cuenta',
    hero_cta: 'Crear una campaña',
    hero_cta2: 'Ver campañas',
    hero_stats_campaigns: 'campañas',
    hero_stats_donors: 'donantes',
    hero_stats_raised: 'recaudado',
    sec_urgent: 'Campañas urgentes',
    sec_urgent_sub: 'Estas causas necesitan ayuda inmediata',
    sec_recent: 'Campañas recientes',
    sec_recent_sub: 'Recién abiertas por la comunidad',
    sec_closed: 'Campañas finalizadas',
    sec_closed_sub: 'Resultados y uso de fondos',
    card_raised: 'Recaudado',
    card_goal: 'Meta',
    card_daysleft: 'días restantes',
    card_closed: 'Finalizada',
    card_cancelled: 'Cancelada',
    card_viewall: 'Ver todas',
    card_view: 'Ver campaña',
    card_urgent: 'Urgente',
    how_title: '¿Cómo funciona?',
    how_step1_title: 'Crea tu campaña',
    how_step1_text: 'Regístrate, describe tu causa y publica tu campaña por una tarifa única de $5',
    how_step2_title: 'Recibe donaciones',
    how_step2_text: 'Comparte tu campaña. Los donantes depositan directamente a tu cuenta bancaria',
    how_step3_title: 'Informa el progreso',
    how_step3_text: 'Al finalizar, comparte con fotos cómo se usaron los fondos',
    empty_none: 'No hay campañas que mostrar todavía',

    // campaigns list
    list_title: 'Campañas',
    list_subtitle: 'Explora las causas de la comunidad',
    filter_all: 'Todas',
    filter_open: 'Abiertas',
    filter_closed: 'Finalizadas',
    filter_urgent: 'Urgentes',
    list_empty: 'No se encontraron campañas con ese filtro',

    // campaign detail
    c_created: 'Creada el',
    c_raised: 'Recaudado',
    c_goal: 'Meta',
    c_daysleft: 'días restantes',
    c_ended: 'Campaña finalizada',
    c_organizer: 'Organizador',
    c_anonymous: 'Donante anónimo',
    c_status_open: 'Abierta',
    c_status_closed: 'Finalizada',
    c_status_cancelled: 'Cancelada',
    c_status_refunded: 'Reembolsada',
    c_status_invalid: 'Inválida',
    c_donate: 'Donar ahora',
    c_donate_title: 'Hacer una donación',
    c_donate_info: 'Realiza tu depósito directo a la cuenta del organizador y confirma aquí tu aporte',
    c_amount: 'Monto (USD)',
    c_bankname: 'Nombre del banco',
    c_bankname_ph: 'Banco desde el que depositaste',
    c_confnum: 'Número de confirmación',
    c_confnum_ph: 'Número de confirmación del depósito',
    c_yourname: 'Tu nombre (opcional)',
    c_yourname_ph: 'Dejar vacío para donar de forma anónima',
    c_anon_note: 'Puedes donar de forma anónima dejando el nombre vacío',
    c_submit_donation: 'Confirmar donación',
    c_bank_title: 'Cuenta bancaria del organizador',
    c_bank_name: 'Banco',
    c_bank_account: 'Cuenta',
    c_bank_holder: 'Titular',
    c_bank_note: 'Realiza tu depósito directamente a esta cuenta y luego confirma tu donación',
    c_donations_title: 'Donaciones',
    c_donations_empty: 'Aún no hay donaciones confirmadas',
    c_progress_title: 'Progreso y uso de fondos',
    c_progress_empty: 'El organizador aún no ha publicado actualizaciones',
    c_postprogress: 'Publicar actualización',
    c_images: 'Galería',
    c_closed_note: 'Esta campaña fue finalizada. Gracias a todos los que apoyaron',
    c_cancelled_note: 'Esta campaña fue cancelada',
    c_invalid_note: 'Esta campaña fue marcada como inválida',
    c_share: 'Compartir',
    c_copied: 'Enlace copiado',
    c_login_to_donate: 'Inicia sesión para donar',

    // donation
    don_thanks: 'Gracias por tu donación',
    don_success: 'Tu donación fue registrada. El organizador la confirmará cuando verifique el depósito en su cuenta',
    don_confirmed: 'Confirmada',
    don_pending: 'Pendiente',
    don_cancelled: 'Cancelada',
    don_refunded: 'Reembolsada',
    don_invalid: 'Inválida',

    // create campaign
    create_title: 'Crea tu campaña de donación',
    create_subtitle: 'Publica tu causa por una tarifa única de $5 depositada a la cuenta de '+config.appName,
    create_fee_title: 'Tarifa de publicación',
    create_fee_text: 'El costo para publicar una campaña es de $5. Depósitalo a la cuenta de '+config.appName+' y tu campaña se publicará de inmediato',
    create_bank_title: 'Cuenta de '+config.appName,
    create_c_title: 'Título de la campaña',
    create_c_title_ph: 'Nombre corto y claro de tu causa',
    create_c_desc: 'Descripción',
    create_c_desc_ph: 'Cuenta la historia de tu causa, a quién ayuda y cómo se usarán los fondos',
    create_c_goal: 'Meta de recaudación (USD)',
    create_c_end: 'Fecha de cierre',
    create_c_end_note: 'La campaña se cierra automáticamente este día',
    create_c_bankname: 'Banco del organizador',
    create_c_bankaccount: 'Número de cuenta',
    create_c_bankholder: 'Titular de la cuenta',
    create_c_images: 'Imágenes (hasta 10)',
    create_c_images_note: 'JPG, PNG, WEBP o GIF. Máximo 1 MB por imagen',
    create_c_submit: 'Publicar campaña',
    create_success: '¡Tu campaña fue publicada!',
    create_fee_missing: 'Debes confirmar que depositaste la tarifa de publicación',
    create_confirm_fee: 'Confirmo que deposité la tarifa de $5 a la cuenta de '+config.appName,

    // payment methods
    c_pay_title: 'Métodos de pago',
    pay_bank: 'Cuenta bancaria',
    pay_paypal: 'PayPal',
    pay_zelle: 'Zelle',
    pay_binance: 'Binance',
    pay_crypto: 'Cripto',
    pay_paypal_email: 'Email de PayPal',
    pay_zelle_email: 'Email de Zelle',
    pay_binance_id: 'ID de Binance',
    pay_crypto_net: 'Red',
    pay_crypto_coin: 'Moneda',
    pay_crypto_addr: 'Dirección',
    pay_paypal_ph: 'tuemail@ejemplo.com',
    pay_zelle_ph: 'tuemail@ejemplo.com',
    pay_binance_ph: 'ID de usuario de Binance',
    pay_crypto_net_ph: 'Ej: BEP-20, ERC-20, TRC-20',
    pay_crypto_coin_ph: 'Ej: USDT, BTC, ETH',
    pay_crypto_addr_ph: 'Dirección de tu billetera',

    // edit campaign
    edit: 'Editar',
    edit_title: 'Editar campaña',
    edit_subtitle: 'Actualiza los datos de tu campaña',
    edit_submit: 'Guardar cambios',
    edit_done: 'La campaña fue actualizada',
    edit_images_note: 'Agrega imágenes nuevas a la campaña (máximo 10 en total)',
    edit_current_images: 'Imágenes actuales',
    img_expand: 'Ampliar imagen',
    img_close: 'Cerrar',

    // my campaigns
    my_title: 'Mis campañas',
    my_empty: 'Aún no has creado campañas',
    my_create: 'Crear mi primera campaña',
    my_close: 'Cerrar campaña',
    my_close_confirm: '¿Cerrar esta campaña?',
    my_manage: 'Gestionar',
    my_donations: 'Donaciones',
    my_donations_empty: 'Sin donaciones todavía',
    my_confirm: 'Confirmar',
    my_cancel: 'Cancelar',
    my_addprogress: 'Añadir actualización',
    my_noprogress: 'La campaña aún no está finalizada. Podrás publicar actualizaciones al cerrarla',
    my_pending: 'Pendientes',
    my_confirmed: 'Confirmadas',
    my_donor: 'Donante',
    my_amount: 'Monto',
    my_date: 'Fecha',
    my_bank: 'Banco',
    my_conf: 'Confirmación',
    my_status: 'Estado',

    // auth
    auth_register_title: 'Crear cuenta',
    auth_register_sub: 'Regístrate para crear campañas o donar',
    auth_login_title: 'Iniciar sesión',
    auth_login_sub: 'Accede a tu cuenta de '+config.appName,
    auth_name: 'Nombre completo',
    auth_userid: 'Nombre de usuario',
    auth_userid_hint: 'Identificador único en minúsculas, sin espacios',
    auth_govid: 'Documento de identidad',
    auth_address: 'Dirección',
    auth_email: 'Correo electrónico',
    auth_phone: 'Teléfono',
    auth_country: 'País',
    auth_password: 'Contraseña',
    auth_confirm: 'Confirmar contraseña',
    auth_submit: 'Registrarse',
    auth_login_btn: 'Entrar',
    auth_forgot: '¿Olvidaste tu contraseña?',
    auth_noaccount: '¿No tienes cuenta?',
    auth_hasaccount: '¿Ya tienes cuenta?',
    auth_register_link: 'Regístrate aquí',
    auth_login_link: 'Inicia sesión aquí',
    auth_forgot_title: 'Recuperar contraseña',
    auth_forgot_sub: 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña',
    auth_send: 'Enviar enlace',
    auth_back: 'Volver al inicio',
    auth_reset_title: 'Nueva contraseña',
    auth_reset_sub: 'Elige una nueva contraseña para tu cuenta',
    auth_reset_btn: 'Guardar contraseña',
    auth_reset_sent: 'Si el correo existe, recibirás un enlace de recuperación',
    auth_reset_done: 'Tu contraseña fue actualizada. Ya puedes iniciar sesión',
    auth_required: 'Todos los campos obligatorios deben completarse',
    auth_email_used: 'Ese correo ya está registrado',
    auth_user_used: 'Ese nombre de usuario ya está en uso',
    auth_pass_mismatch: 'Las contraseñas no coinciden',
    auth_pass_short: 'La contraseña debe tener al menos 6 caracteres',
    auth_invalid: 'Correo o contraseña incorrectos',
    auth_notfound: 'No se encontró la cuenta',
    auth_token_invalid: 'El enlace de recuperación no es válido o expiró',
    auth_bad_userid: 'El nombre de usuario solo puede contener letras minúsculas, números, puntos, guiones y guiones bajos',
    create_bank_required: 'Debes indicar los datos bancarios para recibir las donaciones',
    create_bad_date: 'La fecha de cierre debe ser una fecha futura',

    // dashboard
    dash_title: 'Panel de administración',
    dash_subtitle: 'Resumen de la plataforma',
    dash_campaigns: 'Campañas',
    dash_open: 'Abiertas',
    dash_closed: 'Finalizadas',
    dash_urgent: 'Urgentes',
    dash_donations: 'Donaciones',
    dash_total_raised: 'Total confirmado',
    dash_users: 'Usuarios',
    dash_latest_campaigns: 'Últimas campañas',
    dash_latest_donations: 'Últimas donaciones',
    dash_latest_users: 'Últimos usuarios',
    dash_actions: 'Acciones',
    dash_deactivate: 'Desactivar',
    dash_activate: 'Activar',
    dash_mark_urgent: 'Marcar urgente',
    dash_unmark_urgent: 'Quitar urgente',
    dash_no_data: 'Sin datos todavía',
    dash_title_c: 'Título',
    dash_org: 'Organizador',
    dash_created: 'Creada',
    dash_donor: 'Donante',
    dash_amount: 'Monto',
    dash_status: 'Estado',

    // progress form
    prog_title: 'Publicar actualización',
    prog_subtitle: 'Comparte cómo se están usando los fondos de la campaña',
    prog_p_title: 'Título de la actualización',
    prog_p_title_ph: 'Por ejemplo: primera entrega de alimentos',
    prog_p_text: 'Descripción',
    prog_p_text_ph: 'Detalla el avance y el uso de los fondos',
    prog_p_images: 'Imágenes (opcional)',
    prog_p_images_note: 'JPG, PNG, WEBP o GIF. Máximo 1 MB por imagen',
    prog_p_submit: 'Publicar actualización',
    prog_success: 'Actualización publicada',

    // errors
    err_notfound: 'No encontrado',
    err_unauthorized: 'Debes iniciar sesión',
    err_forbidden: 'No tienes permiso para realizar esta acción',
    err_upload_type: 'Solo se permiten imágenes JPG, PNG, WEBP o GIF',
    err_upload_size: 'Cada imagen debe pesar menos de 1 MB',
    err_upload_max: 'Máximo 10 imágenes por campaña',
    err_fee: 'La tarifa de publicación es de $5',
    err_amount: 'El monto debe ser mayor que cero',
    err_server: 'Ocurrió un error. Intenta nuevamente',
    err_campaign_closed: 'Esta campaña no acepta donaciones',
    err_campaign_own: 'No puedes donar a tu propia campaña',
    err_bad_request: 'Solicitud inválida',
    err_404_title: 'Página no encontrada',
    err_404_text: 'La página que buscas no existe',

    // misc
    currency: '$',
    days: 'días',
    today: 'Hoy',
    view: 'Ver',
    back: 'Volver',
    learn_more: 'Saber más',
    open: 'Abierta',
    closed: 'Finalizada'
  },

  en: {
    // common
    appname: config.appName,
    tagline: 'Help those in need',
    nav_home: 'Home',
    nav_campaigns: 'All campaigns',
    nav_create: 'Start a campaign',
    nav_mycampaigns: 'My campaigns',
    nav_dashboard: 'Dashboard',
    nav_login: 'Log in',
    nav_register: 'Sign up',
    nav_logout: 'Log out',
    nav_hello: 'Hello',
    footer_about: config.appName+' is a platform to create donation campaigns and support causes that transform lives',
    footer_links: 'Links',
    footer_legal: 'Terms and privacy',
    footer_contact: 'Contact',
    footer_rights: 'All rights reserved',
    footer_lang: 'Language',
    lang_es: 'Español',
    lang_en: 'English',
    theme_light: 'Light mode',
    theme_dark: 'Dark mode',

    // hero / landing
    hero_title: 'Be part of the change',
    hero_subtitle: 'Create a donation campaign or support the causes you care about. Every contribution counts',
    hero_cta: 'Start a campaign',
    hero_cta2: 'Browse campaigns',
    hero_stats_campaigns: 'campaigns',
    hero_stats_donors: 'donors',
    hero_stats_raised: 'raised',
    sec_urgent: 'Urgent campaigns',
    sec_urgent_sub: 'These causes need immediate help',
    sec_recent: 'Recent campaigns',
    sec_recent_sub: 'Freshly opened by the community',
    sec_closed: 'Completed campaigns',
    sec_closed_sub: 'Outcomes and use of funds',
    card_raised: 'Raised',
    card_goal: 'Goal',
    card_daysleft: 'days left',
    card_closed: 'Completed',
    card_cancelled: 'Cancelled',
    card_viewall: 'View all',
    card_view: 'View campaign',
    card_urgent: 'Urgent',
    how_title: 'How it works',
    how_step1_title: 'Create your campaign',
    how_step1_text: 'Sign up, describe your cause and publish your campaign for a one-time fee of $5',
    how_step2_title: 'Receive donations',
    how_step2_text: 'Share your campaign. Donors deposit directly to your bank account',
    how_step3_title: 'Report progress',
    how_step3_text: 'When completed, share with photos how the funds were used',
    empty_none: 'There are no campaigns to show yet',

    // campaigns list
    list_title: 'Campaigns',
    list_subtitle: 'Explore the causes of the community',
    filter_all: 'All',
    filter_open: 'Open',
    filter_closed: 'Completed',
    filter_urgent: 'Urgent',
    list_empty: 'No campaigns found with that filter',

    // campaign detail
    c_created: 'Created on',
    c_raised: 'Raised',
    c_goal: 'Goal',
    c_daysleft: 'days left',
    c_ended: 'Campaign completed',
    c_organizer: 'Organizer',
    c_anonymous: 'Anonymous donor',
    c_status_open: 'Open',
    c_status_closed: 'Completed',
    c_status_cancelled: 'Cancelled',
    c_status_refunded: 'Refunded',
    c_status_invalid: 'Invalid',
    c_donate: 'Donate now',
    c_donate_title: 'Make a donation',
    c_donate_info: 'Make your direct deposit to the organizer account and confirm your contribution here',
    c_amount: 'Amount (USD)',
    c_bankname: 'Bank name',
    c_bankname_ph: 'Bank you deposited from',
    c_confnum: 'Confirmation number',
    c_confnum_ph: 'Deposit confirmation number',
    c_yourname: 'Your name (optional)',
    c_yourname_ph: 'Leave empty to donate anonymously',
    c_anon_note: 'You can donate anonymously by leaving the name empty',
    c_submit_donation: 'Confirm donation',
    c_bank_title: 'Organizer bank account',
    c_bank_name: 'Bank',
    c_bank_account: 'Account',
    c_bank_holder: 'Account holder',
    c_bank_note: 'Make your deposit directly to this account and then confirm your donation',
    c_donations_title: 'Donations',
    c_donations_empty: 'There are no confirmed donations yet',
    c_progress_title: 'Progress and use of funds',
    c_progress_empty: 'The organizer has not posted updates yet',
    c_postprogress: 'Post update',
    c_images: 'Gallery',
    c_closed_note: 'This campaign is completed. Thank you to everyone who supported it',
    c_cancelled_note: 'This campaign was cancelled',
    c_invalid_note: 'This campaign was marked as invalid',
    c_share: 'Share',
    c_copied: 'Link copied',
    c_login_to_donate: 'Log in to donate',

    // donation
    don_thanks: 'Thank you for your donation',
    don_success: 'Your donation was recorded. The organizer will confirm it once the deposit is verified in their account',
    don_confirmed: 'Confirmed',
    don_pending: 'Pending',
    don_cancelled: 'Cancelled',
    don_refunded: 'Refunded',
    don_invalid: 'Invalid',

    // create campaign
    create_title: 'Create your donation campaign',
    create_subtitle: 'Publish your cause for a one-time fee of $5 deposited to the '+config.appName+' account',
    create_fee_title: 'Publication fee',
    create_fee_text: 'The cost to publish a campaign is $5. Deposit it to the '+config.appName+' account and your campaign will be published right away',
    create_bank_title: config.appName+' account',
    create_c_title: 'Campaign title',
    create_c_title_ph: 'Short, clear name for your cause',
    create_c_desc: 'Description',
    create_c_desc_ph: 'Tell the story of your cause, who it helps and how the funds will be used',
    create_c_goal: 'Fundraising goal (USD)',
    create_c_end: 'Closing date',
    create_c_end_note: 'The campaign closes automatically on this date',
    create_c_bankname: 'Organizer bank',
    create_c_bankaccount: 'Account number',
    create_c_bankholder: 'Account holder',
    create_c_images: 'Images (up to 10)',
    create_c_images_note: 'JPG, PNG, WEBP or GIF. Max 1 MB per image',
    create_c_submit: 'Publish campaign',
    create_success: 'Your campaign was published!',
    create_fee_missing: 'You must confirm that you deposited the publication fee',
    create_confirm_fee: 'I confirm that I deposited the $5 fee to the '+config.appName+' account',

    // payment methods
    c_pay_title: 'Payment methods',
    pay_bank: 'Bank account',
    pay_paypal: 'PayPal',
    pay_zelle: 'Zelle',
    pay_binance: 'Binance',
    pay_crypto: 'Crypto',
    pay_paypal_email: 'PayPal email',
    pay_zelle_email: 'Zelle email',
    pay_binance_id: 'Binance ID',
    pay_crypto_net: 'Network',
    pay_crypto_coin: 'Coin',
    pay_crypto_addr: 'Wallet address',
    pay_paypal_ph: 'you@example.com',
    pay_zelle_ph: 'you@example.com',
    pay_binance_ph: 'Binance user ID',
    pay_crypto_net_ph: 'e.g. BEP-20, ERC-20, TRC-20',
    pay_crypto_coin_ph: 'e.g. USDT, BTC, ETH',
    pay_crypto_addr_ph: 'Your wallet address',

    // edit campaign
    edit: 'Edit',
    edit_title: 'Edit campaign',
    edit_subtitle: 'Update your campaign details',
    edit_submit: 'Save changes',
    edit_done: 'The campaign was updated',
    edit_images_note: 'Add new images to the campaign (max 10 total)',
    edit_current_images: 'Current images',
    img_expand: 'Expand image',
    img_close: 'Close',

    // my campaigns
    my_title: 'My campaigns',
    my_empty: 'You have not created campaigns yet',
    my_create: 'Create my first campaign',
    my_close: 'Close campaign',
    my_close_confirm: 'Close this campaign?',
    my_manage: 'Manage',
    my_donations: 'Donations',
    my_donations_empty: 'No donations yet',
    my_confirm: 'Confirm',
    my_cancel: 'Cancel',
    my_addprogress: 'Add update',
    my_noprogress: 'The campaign is not completed yet. You can post updates once it is closed',
    my_pending: 'Pending',
    my_confirmed: 'Confirmed',
    my_donor: 'Donor',
    my_amount: 'Amount',
    my_date: 'Date',
    my_bank: 'Bank',
    my_conf: 'Confirmation',
    my_status: 'Status',

    // auth
    auth_register_title: 'Create account',
    auth_register_sub: 'Sign up to create campaigns or donate',
    auth_login_title: 'Log in',
    auth_login_sub: 'Access your '+config.appName+' account',
    auth_name: 'Full name',
    auth_userid: 'Username',
    auth_userid_hint: 'Unique identifier in lowercase, no spaces',
    auth_govid: 'Government ID',
    auth_address: 'Address',
    auth_email: 'Email',
    auth_phone: 'Phone',
    auth_country: 'Country',
    auth_password: 'Password',
    auth_confirm: 'Confirm password',
    auth_submit: 'Sign up',
    auth_login_btn: 'Log in',
    auth_forgot: 'Forgot your password?',
    auth_noaccount: 'Do not have an account?',
    auth_hasaccount: 'Already have an account?',
    auth_register_link: 'Sign up here',
    auth_login_link: 'Log in here',
    auth_forgot_title: 'Recover password',
    auth_forgot_sub: 'Enter your email and we will send you a link to reset your password',
    auth_send: 'Send link',
    auth_back: 'Back to home',
    auth_reset_title: 'New password',
    auth_reset_sub: 'Choose a new password for your account',
    auth_reset_btn: 'Save password',
    auth_reset_sent: 'If the email exists, you will receive a recovery link',
    auth_reset_done: 'Your password was updated. You can log in now',
    auth_required: 'All required fields must be filled in',
    auth_email_used: 'That email is already registered',
    auth_user_used: 'That username is already in use',
    auth_pass_mismatch: 'The passwords do not match',
    auth_pass_short: 'The password must be at least 6 characters',
    auth_invalid: 'Incorrect email or password',
    auth_notfound: 'Account not found',
    auth_token_invalid: 'The recovery link is not valid or has expired',
    auth_bad_userid: 'The username may only contain lowercase letters, numbers, dots, dashes and underscores',
    create_bank_required: 'You must provide bank details to receive donations',
    create_bad_date: 'The closing date must be a future date',

    // dashboard
    dash_title: 'Administration dashboard',
    dash_subtitle: 'Platform overview',
    dash_campaigns: 'Campaigns',
    dash_open: 'Open',
    dash_closed: 'Completed',
    dash_urgent: 'Urgent',
    dash_donations: 'Donations',
    dash_total_raised: 'Total confirmed',
    dash_users: 'Users',
    dash_latest_campaigns: 'Latest campaigns',
    dash_latest_donations: 'Latest donations',
    dash_latest_users: 'Latest users',
    dash_actions: 'Actions',
    dash_deactivate: 'Deactivate',
    dash_activate: 'Activate',
    dash_mark_urgent: 'Mark urgent',
    dash_unmark_urgent: 'Remove urgent',
    dash_no_data: 'No data yet',
    dash_title_c: 'Title',
    dash_org: 'Organizer',
    dash_created: 'Created',
    dash_donor: 'Donor',
    dash_amount: 'Amount',
    dash_status: 'Status',

    // progress form
    prog_title: 'Post update',
    prog_subtitle: 'Share how the campaign funds are being used',
    prog_p_title: 'Update title',
    prog_p_title_ph: 'For example: first food delivery',
    prog_p_text: 'Description',
    prog_p_text_ph: 'Detail the progress and use of funds',
    prog_p_images: 'Images (optional)',
    prog_p_images_note: 'JPG, PNG, WEBP or GIF. Max 1 MB per image',
    prog_p_submit: 'Post update',
    prog_success: 'Update published',

    // errors
    err_notfound: 'Not found',
    err_unauthorized: 'You must log in',
    err_forbidden: 'You do not have permission to perform this action',
    err_upload_type: 'Only JPG, PNG, WEBP or GIF images are allowed',
    err_upload_size: 'Each image must be smaller than 1 MB',
    err_upload_max: 'Maximum 10 images per campaign',
    err_fee: 'The publication fee is $5',
    err_amount: 'The amount must be greater than zero',
    err_server: 'Something went wrong. Please try again',
    err_campaign_closed: 'This campaign is not accepting donations',
    err_campaign_own: 'You cannot donate to your own campaign',
    err_bad_request: 'Invalid request',
    err_404_title: 'Page not found',
    err_404_text: 'The page you are looking for does not exist',

    // misc
    currency: '$',
    days: 'days',
    today: 'Today',
    view: 'View',
    back: 'Back',
    learn_more: 'Learn more',
    open: 'Open',
    closed: 'Completed'
  }
};

module.exports = lang;
